name: Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check_out
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17
      - name: Build the applicaation
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Build Docker Image
        uses: actions/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_USERNAME}}/Spring_boot:latest
      - name: Login to Docker
        users: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: $ {{secrets.DOCKER_TOKEN}}
      - name: Push to Docker Hub
        users: actions/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME}}/Spring_boot:latest