name: Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper Git commands

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Build the application
        run: |
          mvn clean package -DskipTests

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/spring-boot:${{ github.sha }}

      - name: Deploy to Environment (Replace with your deployment steps)
        uses: your-deployment-action@v1  # Replace with your deployment action
        with:
        # Configuration for your deployment
